name: Deploy to Server

on:
  push:
    branches:
      - main  # Запускайте workflow при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Убедитесь, что версия Go соответствует вашей

      - name: Build project
        run: go build -o myapp ./..

      - name: Copy files via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -r ./myapp root@62.109.5.203:/path/to/your/project
          ssh -i private_key root@62.109.5.203 'bash -s' << 'EOF'
            cd /path/to/your/project
            ./myapp &
          EOF
        shell: bash

      - name: Clean up
        run: rm private_key
